apiVersion: batch/v1
kind: Job
metadata:
  name: producer-job
  namespace: lakehouse
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: producer
        image: confluentinc/cp-kafka:7.4.0
        command:
        - sh
        - -c
        - |
          for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30; do
            JSON="{\"vehicleId\":\"CAR_$i\",\"type\":\"car\",\"latitude\":48.85,\"longitude\":2.35,\"battery\":75,\"timestamp\":$(date +%s)000}"
            echo "$JSON" | kafka-console-producer --bootstrap-server kafka:9092 --topic vehicles-events
            echo "Event $i sent"
            sleep 0.1
          done
          echo "All 30 events sent"
      restartPolicy: Never
  backoffLimit: 3