apiVersion: batch/v1
kind: Job
metadata:
  name: producer-job
  namespace: lakehouse
spec:
  template:
    spec:
      containers:
      - name: producer
        image: confluentinc/cp-kafka:7.4.0
        command: ["/bin/bash"]
        args:
          - -c
          - |
            for i in {1..30}; do
              echo "{\"vehicleId\":\"CAR_$i\",\"type\":\"car\",\"latitude\":48.8566,\"longitude\":2.3522,\"battery\":75,\"timestamp\":$(date +%s)000}" | \
              kafka-console-producer --bootstrap-server kafka:9092 --topic vehicles-events
            done
            echo "✅ 30 messages envoyés"
      restartPolicy: Never
  backoffLimit: 2